# 매매 도메인이 broker에 기대하는 좁은 인터페이스 (ISP)
# KIS facade가 구조적으로 충족 — 상속 불필요 (structural Protocol)
from typing import Protocol, runtime_checkable

# 시세/지표 조회 포트
@runtime_checkable
class Quotes(Protocol):
    async def raw(self, code: str) -> int: ...
    async def price(self, code: str) -> dict: ...
    async def daily(self, code: str, count: int = 60) -> list[dict]: ...
    async def c15(self, code: str) -> list[dict]: ...
    async def indices(self) -> list[dict]: ...

# 계좌/잔고 조회 포트
@runtime_checkable
class Account(Protocol):
    async def holdings(self) -> tuple[dict[str, dict], dict]: ...
    async def cash(self) -> int: ...

# 주문 실행 포트
@runtime_checkable
class Orders(Protocol):
    async def buy(self, code: str, qty: int) -> dict: ...
    async def sell(self, code: str, qty: int) -> dict: ...
